services:
  - type: web
    name: resume-builder
    runtime: python
    buildCommand: |
      # Install Node.js
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs
      # Install Python dependencies
      pip install -r requirements.txt
      # Install Node dependencies and Chrome
      npm install
      npm install puppeteer
    startCommand: gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT